# -*- coding: utf-8 -*-
"""Razorpay_model_traning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RLM0h_hus_KxcibmnxDbz3uAbJpnfH3A

## 1. Environment Setup
"""

# Install necessary libraries
!pip install pandas numpy scikit-learn xgboost lightgbm joblib matplotlib seaborn

# Import libraries
import pandas as pd
import numpy as np
import sklearn
import xgboost
import lightgbm
import joblib
import matplotlib.pyplot as plt
import seaborn as sns

print('All required libraries imported successfully.')

"""## 2. Data Ingestion and Initial Exploration"""

# Load the CSV file
file_path = '/content/synthetic_data_set.csv'
df = pd.read_csv(file_path)

print(f'Dataset loaded from: {file_path}')

# Convert 'created_at' to a datetime column using mixed format inference and error handling
df['created_at'] = pd.to_datetime(df['created_at'], format='mixed', dayfirst=True, errors='coerce')

print('Converted `created_at` column to datetime using mixed format inference.')

# Print dataset shape
print(f'Dataset shape: {df.shape}')

# Print summary statistics
print('\nSummary Statistics:')
display(df.describe(include='all'))

# Check for any null or missing values
print('\nNull/Missing Values per column:')
display(df.isnull().sum())

# Print concise summary of the DataFrame
print('\nDataFrame Info:')
df.info()

"""## 3. Feature Engineering"""

# Convert 'amount_inr' to numeric, coercing errors
df['amount_inr'] = pd.to_numeric(df['amount_inr'], errors='coerce')

# Convert 'attempt_number' to numeric, coercing errors
df['attempt_number'] = pd.to_numeric(df['attempt_number'], errors='coerce')

# Convert 'customer_success_rate' to numeric, coercing errors
df['customer_success_rate'] = pd.to_numeric(df['customer_success_rate'], errors='coerce')

print('Converted `amount_inr`, `attempt_number`, and `customer_success_rate` to numeric types.')

# 1. failure_severity
failure_severity_map = {
    'NETWORK_TIMEOUT': 1,
    'INSUFFICIENT_BALANCE': 2,
    'BANK_DECLINE': 3,
    'EXPIRED_CARD': 4,
    'RISK_FLAGGED': 4
}
df['failure_severity'] = df['failure_code'].map(failure_severity_map).fillna(0).astype(int)

# 2. retry_decay: Calculate 1 / (attempt_number^1.5)
df['retry_decay'] = 1 / (df['attempt_number']**1.5)

# 3. reliability_index: Multiply customer_success_rate by customer tier weight
customer_tier_weights = {
    'LOW': 0.5,
    'MEDIUM': 1.0,
    'HIGH': 1.5
}
df['customer_tier_weight'] = df['customer_value'].map(customer_tier_weights)
df['reliability_index'] = df['customer_success_rate'] * df['customer_tier_weight']

# 4. is_high_value: Binary flag (1 if amount_inr >= 50000, else 0)
df['is_high_value'] = (df['amount_inr'] >= 50000).astype(int)

# 5. expected_value_baseline: amount_inr * customer_success_rate
df['expected_value_baseline'] = df['amount_inr'] * df['customer_success_rate']

# 6. amount_log: np.log1p(amount_inr) to normalize amounts
df['amount_log'] = np.log1p(df['amount_inr'])

# 7. hour_of_day: Extracted from created_at
df['hour_of_day'] = df['created_at'].dt.hour

print('Engineered new features: failure_severity, retry_decay, reliability_index, is_high_value, expected_value_baseline, amount_log, and hour_of_day.')

# Output the updated head of the DataFrame
print('\nUpdated DataFrame head with new features:')
display(df.head())

"""## 4. Dataset Preparation for Model Training"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer # Import SimpleImputer
import numpy as np
import pandas as pd # Import pandas if not already imported in this cell

# Define target column
target_column = 'recovered'

# Convert 'recovered' to numeric and handle NaNs in the target
df[target_column] = pd.to_numeric(df[target_column], errors='coerce')

# Drop rows where the target variable is NaN
# This is crucial for stratified split
initial_rows = df.shape[0]
df.dropna(subset=[target_column], inplace=True)
rows_dropped = initial_rows - df.shape[0]
if rows_dropped > 0:
    print(f"Dropped {rows_dropped} rows due to NaN values in the target column '{target_column}'.")

# Convert 'recovered' to int type as it's a binary target
df[target_column] = df[target_column].astype(int)

y = df[target_column]

# Define categorical and numerical features
categorical_features = ['payment_method', 'failure_code', 'failure_source', 'customer_value', 'action_tested']
numeric_features = ['amount_inr', 'amount_log', 'attempt_number', 'customer_success_rate', 'failure_severity', 'retry_decay', 'reliability_index', 'is_high_value', 'expected_value_baseline', 'hour_of_day']

# Combine all features for X from the cleaned DataFrame
X = df[categorical_features + numeric_features]

print(f'Target and feature columns defined. Target has {y.isnull().sum()} NaNs.')
print(f'Features X have {X.isnull().sum().sum()} NaNs initially.')

# Create a column transformer for one-hot encoding categorical features
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features)
    ],
    remainder='passthrough' # Numeric features will be passed through
)

# Apply the preprocessor
# X_processed will now be a numpy array containing both one-hot encoded and original numeric features
X_processed_array = preprocessor.fit_transform(X)

# Get feature names after one-hot encoding
# The ColumnTransformer itself doesn't provide column names for remainder='passthrough' automatically
# For numeric features passed through, we need to add their original names
encoded_feature_names = preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_features)
# The order of columns in X_processed_array will be categorical first, then numeric (passthrough)
all_feature_names = list(encoded_feature_names) + numeric_features

# Convert X_processed_array back to DataFrame for easier NaN handling and maintaining column names
X_processed = pd.DataFrame(X_processed_array, columns=all_feature_names, index=X.index)

# Handle infinite values that might have been introduced (e.g., by division by zero)
# Replace inf with NaN first, then impute these NaNs as well (or use nan_to_num directly)
X_processed.replace([np.inf, -np.inf], np.nan, inplace=True)

# Impute NaN values in the numeric columns of X_processed (including those from inf conversion)
# All features in X_processed are now numeric (float, int)
# Use SimpleImputer to fill missing values (median strategy for robustness)
imputer = SimpleImputer(strategy='median')
X_processed = pd.DataFrame(imputer.fit_transform(X_processed), columns=X_processed.columns, index=X_processed.index)

print(f'Categorical features one-hot encoded. NaNs and Infs in X_processed after imputation: {X_processed.isnull().sum().sum() + np.isinf(X_processed).values.sum()}')

# Get the indices that will be used for train and test
train_indices, test_indices, _, _ = train_test_split(
    X_processed.index, y, test_size=0.2, random_state=42, stratify=y
)

# Use these indices to get the actual data
X_train = X_processed.loc[train_indices].values
X_test = X_processed.loc[test_indices].values
y_train = y.loc[train_indices].values
y_test = y.loc[test_indices].values

# Also create a DataFrame for the test set containing original features, for policy logic
df_test_full = df.loc[test_indices]

print('Dataset split into training and testing sets, and df_test_full created.')

# Print the shape of the resulting datasets
print(f'Shape of X_train: {X_train.shape}')
print(f'Shape of X_test: {X_test.shape}')
print(f'Shape of y_train: {y_train.shape}')
print(f'Shape of y_test: {y_test.shape}')

"""## 5. Model Training and Calibration"""

from xgboost import XGBClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import roc_auc_score, brier_score_loss, classification_report

# Initialize XGBClassifier
base_xgb = XGBClassifier(
    n_estimators=150,
    max_depth=5,
    learning_rate=0.08,
    random_state=42,
    eval_metric='logloss' # Use 'logloss' for binary classification
)

# Wrap with CalibratedClassifierCV
calibrated_xgb = CalibratedClassifierCV(estimator=base_xgb, method='sigmoid', cv=3)

print('XGBClassifier and CalibratedClassifierCV initialized.')

# Fit the calibrated model on training data
print('Fitting calibrated XGBoost model...')
calibrated_xgb.fit(X_train, y_train)
print('Model fitting complete.')

# Predict probabilities on the test set
y_pred_proba = calibrated_xgb.predict_proba(X_test)[:, 1]

# Predict classes on the test set
y_pred = calibrated_xgb.predict(X_test)

# Evaluate on X_test
roc_auc = roc_auc_score(y_test, y_pred_proba)
brier = brier_score_loss(y_test, y_pred_proba)

print(f'ROC-AUC Score: {roc_auc:.4f}')
print(f'Brier Score: {brier:.4f}')
print('\nClassification Report:')
print(classification_report(y_test, y_pred))

"""## 6. Business Impact Evaluation"""

import pandas as pd

# --- Define Realistic Financial Guardrails & Action Costs ---
RETRY_COST = 2.0  # API retry fee
REMINDER_COST = 0.50  # SMS/WhatsApp notification cost
ESCALATION_COST = 30.0  # Human agent operations cost
NUISANCE_PENALTY = 50.0  # Penalty for P(recovery) < 0.35 on a retry

# --- Extract 'amount_inr', 'failure_code' for the test set ---
# We need the original 'amount_inr' and 'failure_code' from the df_test_full for policy logic
# X_test_amount_inr was already extracted, but we need original df_test_full for failure_code

# Total amount at risk (sum of amount_inr in the test set)
total_amount_at_risk = df_test_full['amount_inr'].sum()

print(f"Total Amount at Risk in Test Set: ₹{total_amount_at_risk:,.2f}")

# --- Strategy 1: Baseline A (Do Nothing) ---
# No actions, no costs, no recovery
recovered_A = 0.0
costs_A = 0.0
net_revenue_A = recovered_A - costs_A
actions_taken_A = 0
recovery_rate_A = 0.0

# --- Strategy 2: Baseline B (Generic Blind Retry) ---
# Blindly retries 100% of transactions at RETRY_COST each.
# Recovery only happens if y_test == 1.
total_processed_B = len(df_test_full)
costs_B = total_processed_B * RETRY_COST
recovered_B = df_test_full['amount_inr'][y_test == 1].sum()
net_revenue_B = recovered_B - costs_B
actions_taken_B = total_processed_B
recovery_rate_B = (recovered_B / total_amount_at_risk) * 100 if total_amount_at_risk > 0 else 0.0

# --- Strategy 3: RecoverAI Decision Engine ---
recovered_C = 0.0
costs_C = 0.0
actions_taken_C_count = 0
actions_taken_C_details = {'HUMAN_REVIEW': 0, 'ALTERNATE_METHOD': 0, 'RETRY_6H': 0, 'RETRY_IMMEDIATE': 0, 'PAYMENT_REMINDER': 0, 'DO_NOTHING': 0}

# Loop through each transaction in the test set
for i in range(len(df_test_full)):
    original_payment = df_test_full.iloc[i]
    p_recovery = y_pred_proba[i]  # Calibrated probability from model
    current_amount = original_payment['amount_inr']
    actual_recovery = y_test[i] # 1 if recovered, 0 if not
    failure_code = original_payment['failure_code']

    action = 'DO_NOTHING'
    action_cost = 0.0
    current_nuisance_penalty = 0.0
    expected_value = 0.0 # Initialize expected_value for each transaction

    # Multi-Action Decision Policy for RecoverAI
    if failure_code == 'RISK_FLAGGED' or current_amount >= 50000:
        action = 'HUMAN_REVIEW'
        action_cost = ESCALATION_COST
        # For human review, the recovery probability might be higher or lead to recovery
        # Here we assume if human review is effective, it recovers if y_test==1
        if actual_recovery == 1: # Human review successful
            recovered_C += current_amount

    elif failure_code == 'EXPIRED_CARD':
        action = 'ALTERNATE_METHOD'
        action_cost = REMINDER_COST # Cost for sending link for alternate method
        # If action leads to recovery
        if actual_recovery == 1:
            recovered_C += current_amount

    elif failure_code == 'INSUFFICIENT_BALANCE':
        if p_recovery >= 0.35:
            action = 'RETRY_6H'
            action_cost = RETRY_COST
            if p_recovery < 0.35: # Apply nuisance penalty if condition met for this action
                current_nuisance_penalty = NUISANCE_PENALTY
            if actual_recovery == 1:
                recovered_C += current_amount
        else:
            action = 'DO_NOTHING'

    elif failure_code == 'NETWORK_TIMEOUT':
        if p_recovery >= 0.40:
            action = 'RETRY_IMMEDIATE'
            action_cost = RETRY_COST
            if p_recovery < 0.35: # Apply nuisance penalty if condition met for this action
                current_nuisance_penalty = NUISANCE_PENALTY
            if actual_recovery == 1:
                recovered_C += current_amount
        else:
            action = 'DO_NOTHING'

    # Default catch-all for other failure codes or if no specific policy action was taken above
    # This part was tricky. The prompt stated "If Expected Net Value <= 0 or P(recovery) < 0.20 -> Action is 'DO_NOTHING'."
    # This implies a final check after specific policies. Let's refine EV calculation for decision.

    # The previous if-elif chain already determines an action and its cost.
    # Now calculate expected value of the *chosen* action to potentially override to DO_NOTHING
    if action != 'DO_NOTHING': # Only calculate EV if an action was considered
        expected_value = (p_recovery * current_amount) - (action_cost + current_nuisance_penalty)
        if expected_value <= 0 or p_recovery < 0.20: # Final guardrail to revert to DO_NOTHING
            action = 'DO_NOTHING'
            action_cost = 0.0
            current_nuisance_penalty = 0.0 # No penalty if no action
            # If it's switched to DO_NOTHING, no recovery or cost from this transaction
            # The `recovered_C += current_amount` should only happen if action was actually taken

    # Apply costs for the *final* determined action
    costs_C += (action_cost + current_nuisance_penalty)

    # Update recovery if an action was taken AND it was successful
    # This logic has been moved inside the specific action blocks for clarity and to avoid double counting.
    # If action was DO_NOTHING, no recovery will be added.

    actions_taken_C_details[action] += 1
    if action != 'DO_NOTHING':
        actions_taken_C_count += 1

net_revenue_C = recovered_C - costs_C
recovery_rate_C = (recovered_C / total_amount_at_risk) * 100 if total_amount_at_risk > 0 else 0.0


# --- Create Summary Table ---
summary_data = {
    'Strategy': ['Baseline A (Do Nothing)', 'Baseline B (Generic Blind Retry)', 'RecoverAI Decision Engine'],
    'Total Processed': [len(df_test_full), len(df_test_full), len(df_test_full)],
    'Actions Taken': [actions_taken_A, actions_taken_B, actions_taken_C_count],
    'Action Rate (%)': [round((actions_taken_A / len(df_test_full)) * 100, 2),
                        round((actions_taken_B / len(df_test_full)) * 100, 2),
                        round((actions_taken_C_count / len(df_test_full)) * 100, 2)],
    'Total Cost (INR)': [costs_A, costs_B, costs_C],
    'Gross Recovered (INR)': [recovered_A, recovered_B, recovered_C],
    'Net Recovered (INR)': [net_revenue_A, net_revenue_B, net_revenue_C],
    'Recovery Rate (%)': [recovery_rate_A, recovery_rate_B, recovery_rate_C]
}

summary_df = pd.DataFrame(summary_data)

# Format for better readability
summary_df['Total Cost (INR)'] = summary_df['Total Cost (INR)'].map('₹{:,.2f}'.format)
summary_df['Gross Recovered (INR)'] = summary_df['Gross Recovered (INR)'].map('₹{:,.2f}'.format)
summary_df['Net Recovered (INR)'] = summary_df['Net Recovered (INR)'].map('₹{:,.2f}'.format)

print('\nBusiness Impact Summary:')
display(summary_df)

print('\nRecoverAI Action Breakdown:')
for action, count in actions_taken_C_details.items():
    print(f'- {action}: {count} times')

"""## 7. Model Export and Inference Function"""

import joblib

# --- 1. Save the trained model and preprocessor ---
# Save the calibrated XGBoost model
joblib.dump(calibrated_xgb, 'recovery_model.pkl')
print('Saved calibrated_xgb model as recovery_model.pkl')

# Save the preprocessor (ColumnTransformer which includes OneHotEncoder)
joblib.dump(preprocessor, 'preprocessor.pkl')
print('Saved preprocessor as preprocessor.pkl')

# Save the imputer
joblib.dump(imputer, 'imputer.pkl')
print('Saved imputer as imputer.pkl')

# For the inference function, we'll need the exact feature names post-preprocessing
# and the maps used for feature engineering. We'll define them within the script.

import pandas as pd
import numpy as np
import joblib

# --- Load the saved model components ---
loaded_model = joblib.load('recovery_model.pkl')
loaded_preprocessor = joblib.load('preprocessor.pkl')
loaded_imputer = joblib.load('imputer.pkl')

# --- Re-define constants and feature lists used during training ---
RETRY_COST = 2.0  # API retry fee
REMINDER_COST = 0.50  # SMS/WhatsApp notification cost
ESCALATION_COST = 30.0  # Human agent operations cost
NUISANCE_PENALTY = 50.0 # Penalty for P(recovery) < 0.35 on a retry action

failure_severity_map = {
    'NETWORK_TIMEOUT': 1,
    'INSUFFICIENT_BALANCE': 2,
    'BANK_DECLINE': 3,
    'EXPIRED_CARD': 4,
    'RISK_FLAGGED': 4
}

customer_tier_weights = {
    'LOW': 0.5,
    'MEDIUM': 1.0,
    'HIGH': 1.5
}

categorical_features = ['payment_method', 'failure_code', 'failure_source', 'customer_value', 'action_tested']
numeric_features = ['amount_inr', 'amount_log', 'attempt_number', 'customer_success_rate', 'failure_severity', 'retry_decay', 'reliability_index', 'is_high_value', 'expected_value_baseline', 'hour_of_day']

# `all_feature_names` is globally available from previous steps. If not, it would need to be passed or regenerated here.

def predict_recovery(payment_dict: dict) -> dict:
    """
    Predicts recovery for a single payment and recommends action based on new multi-action policy.

    Args:
        payment_dict (dict): A dictionary representing a single payment transaction
                             (e.g., from a JSON payload).

    Returns:
        dict: A dictionary containing:
            - 'recommended_action': The specific action to take (e.g., 'RETRY_6H', 'HUMAN_REVIEW').
            - 'calibrated_recovery_probability': Probability from 0.0 to 1.0, formatted to 4 decimals.
            - 'expected_net_recovery_inr': Expected net revenue in INR.
            - 'human_escalation_flag': True/False if amount >= ₹50,000 or fraud flag is detected.
            - 'decision_rationale': Brief text explaining the chosen action.
    """
    # 1. Convert to DataFrame for consistent feature engineering
    df_single = pd.DataFrame([payment_dict])

    # 2. Perform Feature Engineering (replicate steps from notebook)
    df_single['amount_inr'] = pd.to_numeric(df_single['amount_inr'], errors='coerce')
    df_single['attempt_number'] = pd.to_numeric(df_single['attempt_number'], errors='coerce')
    df_single['customer_success_rate'] = pd.to_numeric(df_single['customer_success_rate'], errors='coerce')
    df_single['created_at'] = pd.to_datetime(df_single['created_at'], format='mixed', dayfirst=True, errors='coerce')

    df_single['failure_severity'] = df_single['failure_code'].map(failure_severity_map).fillna(0).astype(int)
    df_single['retry_decay'] = df_single['attempt_number'].apply(lambda x: 1 / (x**1.5) if pd.notna(x) and x > 0 else 0)
    df_single['customer_tier_weight'] = df_single['customer_value'].map(customer_tier_weights)
    df_single['reliability_index'] = df_single['customer_success_rate'] * df_single['customer_tier_weight']
    df_single['is_high_value'] = (df_single['amount_inr'] >= 50000).astype(int)
    df_single['expected_value_baseline'] = df_single['amount_inr'] * df_single['customer_success_rate']
    df_single['amount_log'] = np.log1p(df_single['amount_inr'])
    df_single['hour_of_day'] = df_single['created_at'].dt.hour.fillna(0).astype(int)

    # Select features and ensure order matches training data
    X_single_features = df_single[categorical_features + numeric_features]

    # 3. Preprocess and impute
    X_processed_single_array = loaded_preprocessor.transform(X_single_features)
    X_processed_single_df = pd.DataFrame(X_processed_single_array, columns=all_feature_names)
    X_final_single = loaded_imputer.transform(X_processed_single_df)

    # 4. Predict calibrated probability
    p_recovery = loaded_model.predict_proba(X_final_single)[:, 1][0]
    amount_inr_val = df_single['amount_inr'].iloc[0]
    failure_code = payment_dict.get('failure_code') # Get original failure code

    # 5. Determine Recommended Action, Cost, Expected Value, and Rationale
    recommended_action = 'DO_NOTHING'
    action_cost = 0.0
    human_escalation_flag = False
    decision_rationale = "No specific action met criteria or Expected Net Value <= 0."
    nuisance_penalty_applied = 0.0

    # Policy 1: High-value or RISK_FLAGGED for Human Review
    if failure_code == 'RISK_FLAGGED' or amount_inr_val >= 50000:
        recommended_action = 'HUMAN_REVIEW'
        action_cost = ESCALATION_COST
        human_escalation_flag = True
        decision_rationale = "Failure is RISK_FLAGGED or amount is high, requires human review."

    # Policy 2: EXPIRED_CARD for Alternate Method
    elif failure_code == 'EXPIRED_CARD':
        recommended_action = 'ALTERNATE_METHOD'
        action_cost = REMINDER_COST
        decision_rationale = "Card expired, suggesting alternate payment method."

    # Policy 3: INSUFFICIENT_BALANCE for RETRY_6H
    elif failure_code == 'INSUFFICIENT_BALANCE':
        if p_recovery >= 0.35:
            recommended_action = 'RETRY_6H'
            action_cost = RETRY_COST
            decision_rationale = "Insufficient balance, P(recovery) is sufficient for a delayed retry."
            if p_recovery < 0.35: # Nuisance penalty for retry with lower probability
                nuisance_penalty_applied = NUISANCE_PENALTY

    # Policy 4: NETWORK_TIMEOUT for RETRY_IMMEDIATE
    elif failure_code == 'NETWORK_TIMEOUT':
        if p_recovery >= 0.40:
            recommended_action = 'RETRY_IMMEDIATE'
            action_cost = RETRY_COST
            decision_rationale = "Network timeout, P(recovery) is high for an immediate retry."
            if p_recovery < 0.35: # Nuisance penalty for retry with lower probability
                nuisance_penalty_applied = NUISANCE_PENALTY

    # Calculate total action cost including nuisance penalty
    total_action_cost = action_cost + nuisance_penalty_applied

    # Calculate Expected Net Value for the determined action
    # If the action is DO_NOTHING, there's no cost or potential recovery. EV is 0.
    if recommended_action == 'DO_NOTHING':
        expected_net_recovery_inr = 0.0
    else:
        expected_net_recovery_inr = (p_recovery * amount_inr_val) - total_action_cost

    # Final Guardrail: Override to DO_NOTHING if Expected Net Value is <= 0 or P(recovery) is too low
    if (recommended_action not in ['HUMAN_REVIEW', 'ALTERNATE_METHOD']) and (expected_net_recovery_inr <= 0 or p_recovery < 0.20):
        recommended_action = 'DO_NOTHING'
        expected_net_recovery_inr = 0.0 # No net recovery if doing nothing
        decision_rationale = "Expected net value is not positive or P(recovery) is too low to justify intervention."
        total_action_cost = 0.0 # No cost if doing nothing
        human_escalation_flag = False # No escalation if doing nothing

    return {
        'recommended_action': recommended_action,
        'calibrated_recovery_probability': round(float(p_recovery), 4),
        'expected_net_recovery_inr': float(expected_net_recovery_inr),
        'human_escalation_flag': human_escalation_flag,
        'decision_rationale': decision_rationale
    }

print('Inference function `predict_recovery` updated with multi-action policy.')

# --- Demo of the updated inference function ---
print('\n--- Demo of `predict_recovery` function (Updated) ---')

# Example 1: INSUFFICIENT_BALANCE with good P(recovery)
example_payment_1 = {
    'payment_id': 'test_pay_001',
    'customer_id': 'cust_abc',
    'merchant_id': 'mch_xyz',
    'amount_inr': 15000.00,
    'payment_method': 'UPI',
    'failure_code': 'INSUFFICIENT_BALANCE',
    'failure_source': 'bank',
    'attempt_number': 1,
    'customer_success_rate': 0.8,
    'customer_value': 'HIGH',
    'action_tested': 'RETRY',
    'recovered': None,
    'recovered_amount': None,
    'created_at': '2023-03-01 10:00:00'
}

result_1 = predict_recovery(example_payment_1)
print('\nResult for Example 1 (INSUFFICIENT_BALANCE, good P(recovery)):')
display(result_1)

# Example 2: NETWORK_TIMEOUT with good P(recovery)
example_payment_2 = {
    'payment_id': 'test_pay_002',
    'customer_id': 'cust_def',
    'merchant_id': 'mch_uvw',
    'amount_inr': 5000.00,
    'payment_method': 'Credit Card',
    'failure_code': 'NETWORK_TIMEOUT',
    'failure_source': 'network',
    'attempt_number': 1,
    'customer_success_rate': 0.7,
    'customer_value': 'MEDIUM',
    'action_tested': 'RETRY',
    'recovered': None,
    'recovered_amount': None,
    'created_at': '2023-03-01 15:30:00'
}

result_2 = predict_recovery(example_payment_2)
print('\nResult for Example 2 (NETWORK_TIMEOUT, good P(recovery)):')
display(result_2)

# Example 3: EXPIRED_CARD
example_payment_3 = {
    'payment_id': 'test_pay_003',
    'customer_id': 'cust_ghi',
    'merchant_id': 'mch_rst',
    'amount_inr': 1200.00,
    'payment_method': 'Net Banking',
    'failure_code': 'EXPIRED_CARD',
    'failure_source': 'gateway',
    'attempt_number': 1,
    'customer_success_rate': 0.6,
    'customer_value': 'LOW',
    'action_tested': 'DO_NOTHING',
    'recovered': None,
    'recovered_amount': None,
    'created_at': '2023-03-02 08:00:00'
}

result_3 = predict_recovery(example_payment_3)
print('\nResult for Example 3 (EXPIRED_CARD):')
display(result_3)

# Example 4: High-value payment that should flag for human escalation
example_payment_4 = {
    'payment_id': 'test_pay_004',
    'customer_id': 'cust_jkl',
    'merchant_id': 'mch_uvw',
    'amount_inr': 75000.00, # High value
    'payment_method': 'UPI',
    'failure_code': 'INSUFFICIENT_BALANCE',
    'failure_source': 'bank',
    'attempt_number': 1,
    'customer_success_rate': 0.9,
    'customer_value': 'HIGH',
    'action_tested': 'RETRY',
    'recovered': None,
    'recovered_amount': None,
    'created_at': '2023-03-02 09:00:00'
}

result_4 = predict_recovery(example_payment_4)
print('\nResult for Example 4 (High-value payment):')
display(result_4)

# Example 5: RISK_FLAGGED payment
example_payment_5 = {
    'payment_id': 'test_pay_005',
    'customer_id': 'cust_mno',
    'merchant_id': 'mch_pqr',
    'amount_inr': 5000.00,
    'payment_method': 'Credit Card',
    'failure_code': 'RISK_FLAGGED', # Fraud flag
    'failure_source': 'gateway',
    'attempt_number': 1,
    'customer_success_rate': 0.5,
    'customer_value': 'MEDIUM',
    'action_tested': 'RETRY',
    'recovered': None,
    'recovered_amount': None,
    'created_at': '2023-03-03 11:00:00'
}

result_5 = predict_recovery(example_payment_5)
print('\nResult for Example 5 (RISK_FLAGGED payment):')
display(result_5)

# Example 6: Low P(recovery) leading to DO_NOTHING
example_payment_6 = {
    'payment_id': 'test_pay_006',
    'customer_id': 'cust_xyz',
    'merchant_id': 'mch_abc',
    'amount_inr': 1000.00,
    'payment_method': 'UPI',
    'failure_code': 'NETWORK_TIMEOUT',
    'failure_source': 'network',
    'attempt_number': 5,
    'customer_success_rate': 0.1,
    'customer_value': 'LOW',
    'action_tested': 'DO_NOTHING',
    'recovered': None,
    'recovered_amount': None,
    'created_at': '2023-03-03 14:00:00'
}

result_6 = predict_recovery(example_payment_6)
print('\nResult for Example 6 (Low P(recovery)):')
display(result_6)